Repository GSM-MSG/SMS-Android, pull requests merged in 2023-07, with the labels that each got.

#215 🔀 :: (#214) - create the model of my page data
  data/src/main/java/com/msg/sms/data/remote/datasource/user/RemoteUserDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/user/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/user/response/GetMyProfileResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/user/response/LanguageCertificateResponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/UserAPI.kt
  data/src/main/java/com/msg/sms/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/user/response/LanguageCertificateModel.kt
  domain/src/main/java/com/msg/sms/domain/model/user/response/MyProfileModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/UserRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/user/GetMyProfileUseCase.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#217 🔀 : :: CD 스크립트 수정
  .github/workflows/android_cd.yml
Labels: 🌏 Deploy

#218 🔀 :: 패키지 명 수정
  .github/workflows/android_cd.yml
Labels: 🐞 Bug

#216 🔀 :: (#183) - 필터 페이지 퍼블리싱
  .idea/misc.xml
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  design-system/build.gradle.kts
  design-system/src/main/java/com/msg/sms/design/component/button/BoxButton.kt
  design-system/src/main/java/com/msg/sms/design/component/slider/SmsSlider.kt
  design-system/src/main/java/com/msg/sms/design/component/slider/SmsSliderCustomTrack.kt
  design-system/src/main/java/com/msg/sms/design/component/slider/SmsSliderThumbBox.kt
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  design-system/src/main/java/com/msg/sms/design/component/topbar/TopBarComponent.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/sms/presentation/main/ui/base/BaseActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterDetailStackSearchComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterItem.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectionControls.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectionControlsGroup.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorGroup.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSliderComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSliderGroup.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/data/FilterClass.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/data/FilterDepartment.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/data/FilterGrade.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/data/FilterTypeOfEmployment.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/screen/FilterScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#225 🔀 :: (#224) - SmsCustomTextFiled Leading Icon 이슈 해결
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#223 🔀 :: (#221) - GAuth 업데이트 적용
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature
