Repository GSM-MSG/SMS-Android, pull requests merged in 2023-05, with the labels that each got.

#39 🔀 :: (#38) - design system chip component 구현
  design-system/src/main/java/com/msg/sms/design/component/SmsChip.kt
  design-system/src/main/res/drawable/plus_btn_icon.xml
Labels: 1️⃣ Priority: High, ✨ Feature

#32 🔀 :: (#28) - save login token and auto login
  app/build.gradle.kts
  app/src/main/java/com/msg/sms_android/modules/DataStoreModule.kt
  app/src/main/java/com/msg/sms_android/modules/LocalDataSourceModule.kt
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/proguard-rules.pro
  data/src/main/java/com/msg/sms/data/local/datasource/auth/LocalAuthDataSource.kt
  data/src/main/java/com/msg/sms/data/local/datasource/auth/LocalAuthDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/local/key/AuthPreferenceKey.kt
  data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#41 🔀 :: (#37) - add button component
  design-system/src/main/java/com/msg/sms/design/component/button/BoxButton.kt
  design-system/src/main/java/com/msg/sms/design/component/button/ButtonState.kt
  design-system/src/main/java/com/msg/sms/design/component/button/RoundedButton.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#42 🔀 :: (#40) - 디자인 시스템 아이콘 추가
  design-system/src/main/java/com/msg/sms/design/component/SmsChip.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_back_btn.xml
  design-system/src/main/res/drawable/ic_camera.xml
  design-system/src/main/res/drawable/ic_check_btn.xml
  design-system/src/main/res/drawable/ic_delete_btn.xml
  design-system/src/main/res/drawable/ic_filled_plus_btn.xml
  design-system/src/main/res/drawable/ic_open_btn.xml
  design-system/src/main/res/drawable/ic_plus_btn.xml
  design-system/src/main/res/drawable/ic_plus_btn_gray.xml
Labels: 1️⃣ Priority: High, ✨ Feature

#47 🔀 :: (#45) - create text field of design component
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#46 🔀 :: (#43) - 다이얼로그 컴포넌트를 추가헀습니다.
  .gitignore
  design-system/src/main/java/com/msg/sms/design/component/SmsDialog.kt
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#49 🔀 :: (#48) - create component of selector button
  design-system/src/main/java/com/msg/sms/design/component/selector/SmsSelectionControls.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#59 🔀 :: (#58) - 아이콘 색 이슈 해결
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#57 🔀 :: (#50) - 학생 정보 기입 data layer 부분 작성
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/CertificateInformation.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/EnterStudentInformationRequest.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/.gitinit
  data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#60 🔀 :: (#51) - publishing the profile page UI of fill out infomation
  design-system/src/main/java/com/msg/sms/design/component/indicator/PagerIndicator.kt
  design-system/src/main/java/com/msg/sms/design/component/spacer/SmsSpacer.kt
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  design-system/src/main/java/com/msg/sms/design/component/topbar/TopBarComponent.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_profile_btn.xml
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#63 🔀 :: (#62) - 유저 정보기입 domain Layer 로직 작성
  app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
  data/src/main/java/com/msg/sms/data/mapper/.gitinit
  data/src/main/java/com/msg/sms/data/mapper/LoginMapper.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/CertificateInformationModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/EnterStudentInformationRequest.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/.gitinit
  domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/GAuthLoginUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/EnterStudentInformationUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/LoginViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#64 🔀 :: (#61) - create bottom sheet
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/MajorBottomSheet.kt
  design-system/src/main/java/com/msg/sms/design/component/indicator/PagerIndicator.kt
  design-system/src/main/java/com/msg/sms/design/component/selector/MajorSelector.kt
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  design-system/src/main/java/com/msg/sms/design/component/topbar/TopBarComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#68 🔀 :: (#52) - publishing the page of school life
  design-system/src/main/java/com/msg/sms/design/component/text/SmsTitleText.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/SchoolLifeComponent.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#71 🔀 :: (#70) - remove the dependencies related to the android of domain layer
  domain/build.gradle.kts
  domain/src/androidTest/java/com/sms/domain/ExampleInstrumentedTest.kt
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#72 🔀 :: (#53) - publishing the working condition page UI of fill out information
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/SelectorBottomSheet.kt
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_trash_can.xml
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/WorkConditionScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#73 🔀 :: (#54) - create militaryService Page
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/MilitaryServiceScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/MilitaryServiceComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#69 🔀 :: (#67) - 정보 기입 뷰모델 로직 작성
  app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#75 🔀 :: (#56) - create ForeignLanguageScreen
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#74 🔀 :: (#55) - create certificationScreen
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/CertificationScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/CertificationComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#78 🔀 :: (#76) - 이미지 업로드 로직 작성
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
  app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/fileupload/RemoteFileUploadDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/fileupload/RemoteFileUploadDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/fileupload/response/FileUploadResponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/FileUploadAPI.kt
  data/src/main/java/com/msg/sms/data/repository/FileUploadRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/msg/sms/domain/model/fileupload/response/FileUploadResponseModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/FileUploadRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/fileupload/ImageUploadUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FileUploadViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/Event.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/errorHandling.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#81 🔀 :: (#80) - 드림북 업로드 로직 작성
  data/src/main/java/com/msg/sms/data/remote/datasource/fileupload/RemoteFileUploadDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/fileupload/RemoteFileUploadDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/FileUploadAPI.kt
  data/src/main/java/com/msg/sms/data/repository/FileUploadRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/repository/FileUploadRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/fileupload/DreamBookUploadUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FileUploadViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#87 🔀 :: (#83) - save information entered by users
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/SchoolLifeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/MilitaryServiceData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProfileData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/WorkConditionData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#89 🔀 :: (#86) - 드림북 꺼내오는 로직 추가
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/SchoolLifeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/getFileExtension.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/getFileFromUri.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/getFileNameFromUri.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#91 🔀 - 88 store and loading list data of entered by user
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/CertificationComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/CertificationData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#94 🔀 :: (#92) - when login control the page according to type of user
  data/src/main/java/com/msg/sms/data/remote/dto/auth/response/GAuthLoginResponse.kt
  domain/src/main/java/com/msg/sms/domain/model/auth/response/GAuthLoginResponseModel.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#95 🔀 :: (#90) - 권한 요청 로직 작성
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#96 🔀 :: (#93) - get major list from server
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
  app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/major/RemoteMajorDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/major/RemoteMajorDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/major/MajorListResponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/MajorAPI.kt
  data/src/main/java/com/msg/sms/data/repository/MajorRepositoryImpl.kt
  data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
  domain/src/main/java/com/msg/sms/domain/model/major/MajorListModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/MajorRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/major/GetMajorListUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/CertificationComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#99 🔀 :: ($98) - store the login data
  data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
  domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/SaveTheLoginDataUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#102 🔀 :: (#97) - 프로필 사진등록 방식 카메라 촬영 추가
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/ChooseProfilePictureBottomSheet.kt
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/ProfileBottomSheetComponent.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/java/com/msg/sms/design/modifier/smsClickable.kt
  design-system/src/main/res/drawable/ic_camera.xml
  design-system/src/main/res/drawable/ic_gallery.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature
