Repository GSM-MSG/SMS-Android, pull requests merged in 2023-04, with the labels that each got.

#5 🔀 :: (#1) setting android ci
  .github/workflows/android_ci.yml
Labels: ⚙ Setting

#9 🔀 :: (#8) - DI세팅
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  app/src/main/java/com/msg/sms_android/SmsApplication.kt
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  domain/build.gradle.kts
  presentation/build.gradle.kts
Labels: 1️⃣ Priority: High

#12 🔀 :: (#10) - GAuth 의존성 추가
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  settings.gradle.kts
Labels: 1️⃣ Priority: High

#14 🔀 :: (#13) - 디자인 시스템 모듈 생성
  .idea/gradle.xml
  buildSrc/src/main/java/ProjectProperties.kt
  design-system/.gitignore
  design-system/build.gradle.kts
  design-system/consumer-rules.pro
  design-system/proguard-rules.pro
  design-system/src/androidTest/java/com/sms/design_system/ExampleInstrumentedTest.kt
  design-system/src/main/AndroidManifest.xml
  design-system/src/test/java/com/sms/design_system/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High

#16 🔀:: (#15) - set up the package
  data/src/main/kotlin/com/msg/sms/data/local/dao/.gitinit
  data/src/main/kotlin/com/msg/sms/data/local/database/.gitinit
  data/src/main/kotlin/com/msg/sms/data/local/datasource/.gitinit
  data/src/main/kotlin/com/msg/sms/data/local/datastorage/.gitinit
  data/src/main/kotlin/com/msg/sms/data/local/entity/.gitinit
  data/src/main/kotlin/com/msg/sms/data/remote/datasource/.gitinit
  data/src/main/kotlin/com/msg/sms/data/remote/dto/.gitinit
  data/src/main/kotlin/com/msg/sms/data/remote/network/.gitinit
  data/src/main/kotlin/com/msg/sms/data/repository/.gitinit
  data/src/main/kotlin/com/msg/sms/data/util/.gitinit
  domain/src/main/kotlin/com/msg/sms/domain/exception/.gitinit
  domain/src/main/kotlin/com/msg/sms/domain/modal/.gitinit
  domain/src/main/kotlin/com/msg/sms/domain/repository/.gitinit
  domain/src/main/kotlin/com/msg/sms/domain/usecase/.gitinit
  domain/src/main/kotlin/com/msg/sms/domain/util/.gitinit
Labels: 1️⃣ Priority: High, ⚙ Setting

#18 🔀 :: (#17) - package 이름에 오타 수정
  data/src/main/java/com/msg/sms/data/local/dao/.gitinit
  data/src/main/java/com/msg/sms/data/local/database/.gitinit
  data/src/main/java/com/msg/sms/data/local/datasource/.gitinit
  data/src/main/java/com/msg/sms/data/local/datastorage/.gitinit
  data/src/main/java/com/msg/sms/data/local/entity/.gitinit
  data/src/main/java/com/msg/sms/data/remote/datasource/.gitinit
  data/src/main/java/com/msg/sms/data/remote/dto/.gitinit
  data/src/main/java/com/msg/sms/data/remote/network/.gitinit
  data/src/main/java/com/msg/sms/data/repository/.gitinit
  data/src/main/java/com/msg/sms/data/util/.gitinit
  domain/src/main/java/com/msg/sms/domain/exception/.gitinit
  domain/src/main/java/com/msg/sms/domain/model/.gitinit
  domain/src/main/java/com/msg/sms/domain/repository/.gitinit
  domain/src/main/java/com/msg/sms/domain/usecase/.gitinit
  domain/src/main/java/com/msg/sms/domain/util/.gitinit
Labels: 0️⃣ Priority: Critical, 📝 Docs

#21 🔀 :: (#20) - GAuth로 로그인 remote쪽 로직 작성
  .gitignore
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  data/src/main/java/com/msg/sms/data/remote/dto/.gitinit
  data/src/main/java/com/msg/sms/data/remote/dto/auth/request/GAuthLoginRequest.kt
  data/src/main/java/com/msg/sms/data/remote/dto/auth/response/GAuthLoginResponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/.gitinit
  data/src/main/java/com/msg/sms/data/remote/network/api/AuthAPI.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#23 🔀 :: (#22) - GAuth로 로그인 data layer 로직 작성
  app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/.gitinit
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/util/.gitinit
  data/src/main/java/com/msg/sms/data/util/SMSApiHandler.kt
  domain/src/main/java/com/msg/sms/domain/exception/.gitinit
  domain/src/main/java/com/msg/sms/domain/exception/HttpException.kt
  domain/src/main/java/com/msg/sms/domain/exception/NeedLoginException.kt
  domain/src/main/java/com/msg/sms/domain/exception/NoInternetException.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#25 🔀 :: (#22) - 네이밍 변경
  app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#24 🔀 :: (#19) - set up design system
  .gitignore
  design-system/src/main/java/com/msg/sms/design/theme/ColorTheme.kt
  design-system/src/main/java/com/msg/sms/design/theme/SMSTheme.kt
  design-system/src/main/java/com/msg/sms/design/theme/SMSTypography.kt
  design-system/src/main/java/com/msg/sms/design/theme/ThemeGuide.kt
  design-system/src/main/java/com/msg/sms/design/theme/color/LightColor.kt
  design-system/src/main/res/font/pretendard_black.otf
  design-system/src/main/res/font/pretendard_bold.otf
  design-system/src/main/res/font/pretendard_extrabold.otf
  design-system/src/main/res/font/pretendard_extralight.otf
  design-system/src/main/res/font/pretendard_light.otf
  design-system/src/main/res/font/pretendard_medium.otf
  design-system/src/main/res/font/pretendard_regular.otf
  design-system/src/main/res/font/pretendard_semibold.otf
  design-system/src/main/res/font/pretendard_thin.otf
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#30 🔀 :: (#29) - 뷰모델쪽 로직 작성
  app/src/main/AndroidManifest.xml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/MainViewModel.kt
  presentation/src/main/java/com/sms/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/sms/presentation/ui/theme/Shape.kt
  presentation/src/main/java/com/sms/presentation/ui/theme/Theme.kt
  presentation/src/main/java/com/sms/presentation/ui/theme/Type.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#33 🔀 :: (#31) - 로그인 페이지 퍼블리싱
  buildSrc/src/main/java/Versions.kt
  design-system/src/main/java/com/msg/sms/design/theme/SMSTypography.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginButton.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginPageBackGround.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/TopComponent.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/LoginViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/Event.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/errorHandling.kt
  presentation/src/main/res/drawable/login_page_bg.webp
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, ✨ Feature

#36 🔀 :: (#35) - 로그인 페이지 디자인 변경사항 적용
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/TopComponent.kt
  presentation/src/main/res/values/strings.xml
Labels: 2️⃣ Priority: Medium, ⚡️ Simple
