Repository GSM-MSG/SMS-Android, pull requests merged in 2023-09, with the labels that each got.

#353 🔀 :: (#352) - version name 변경
  buildSrc/src/main/java/ProjectProperties.kt
Labels: 🌏 Deploy

#357 🔀 :: (#355) - 이미지 extension이 맞아야만 이미지 업로드 될 수 있도록 변경
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/PhotoPickBottomSheet.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug

#359 🔀 :: (#356) - Change the award date picker on my page
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#360 🔀 :: (#358) - 프로필 세부스택 삭제 기능 구현
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#365 🔀 :: (#361) - resolve error of out app on click portfolio button
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForStudentResponse.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#363 🔀 :: (#362) - 인증제 점수 인풋 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/schoollife/SchoolLifeComponent.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug

#370 🔀 :: (#369) - 희망 연봉 인풋 필드 앱 크래시 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/workcondition/WorkConditionComponent.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug

#374 🔀 :: (#366) - Create the feature of not added change my profile on my page
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/life/SchoolScoreComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WantPayComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/SchoolLifeSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/WorkConditionSection.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#377 🔀 :: (#376) - Change the regex on regular_expression
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#380 🔀 :: (#378) - 이미지 확장자 검사 boolean값 반대로 넘어오던 문제 해결
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/PhotoPickBottomSheet.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#381 🔀 ::(#379) - Change the place holder on my page
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardNameComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardTypeComponent.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#383 🔀 :: (#382) - 학과 및 희망 고용형태 필터링이 진행되지 않던 문제 해결
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorGroup.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/screen/FilterScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug

#386 🔀 :: (#385) - v1.1.2 업데이트를 위한 version code, version name 수정
  buildSrc/src/main/java/ProjectProperties.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#389 🔀 :: (#388) - 메인페이지 리스트 페이지네이션 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#393 🔀 :: (#392) - AuthViewModel SaveToken 변수
  .gitignore
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/index.pb
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#391 🔀 :: (#390) - Remove the not used code in search bar
  design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#395 🔀 :: (#394) - FireBase Clashlytics를 연동합니다.
  app/build.gradle.kts
  app/google-services.json
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature
