Repository GSM-MSG/SMS-Android, pull requests merged in 2023-06, with the labels that each got.

#107 🔀 :: (#100) - add the ability to populate other majors
  data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/SelectorBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProfileData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#109 🔀 :: (#108) - auto login check
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#106 🔀 :: (#105) - 프로필 정보기입 bottom sheet이슈 해결
  data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#110 🔀 :: (#101) - upload the app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: 0️⃣ Priority: Critical, 📝 Docs

#113 🔀 :: (#112) - modify login time format
  data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
  data/src/main/java/com/msg/sms/data/util/DateFormatter.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#115 🔀 :: (#114) - change the status bar color
  app/src/main/res/values/themes.xml
  data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/setTransparentStatusBar.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#118 🔀 :: (#111) - 메인 페이지 UI구현
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_filter_btn.xml
  design-system/src/main/res/drawable/ic_profile_defalut.xml
  design-system/src/main/res/drawable/ic_sms_logo.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/MainScreenTopBar.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListItem.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/data/StudentData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#104 🔀 :: (#103) - 정보기입 뷰 와 뷰모델간 로직 연결
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/EnterStudentInformationRequest.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt
  design-system/src/main/java/com/msg/sms/design/component/SmsDialog.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/EnterStudentInformationRequest.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/SchoolLifeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/SchoolLifeData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/getFileFromUri.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FileUploadViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#123 🔀 :: (#121) - 메인 페이지 api로직을 작성합니다.
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/.gitinit
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentListResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/StudentInformation.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/EnterStudentInformationModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/.gitinit
  domain/src/main/java/com/msg/sms/domain/model/student/response/StudentListModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/StudentModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetStudentListUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#124 🔀 :: (#122) - 리스트 위로 올리는 기능
  design-system/src/main/java/com/msg/sms/design/component/button/ListFloatingButton.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_arrow_upward.xml
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#126 🔀 :: (#120) - publishing the detail page
  design-system/src/main/java/com/msg/sms/design/component/divider/SmsDivider.kt
  design-system/src/main/java/com/msg/sms/design/component/item/TechStackItem.kt
  design-system/src/main/java/com/msg/sms/design/component/profile/ProfileImageComponent.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_book.xml
  design-system/src/main/res/drawable/ic_profile_defalut.xml
  design-system/src/main/res/drawable/ic_profile_default.xml
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentInfoComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/MainScreenTopBar.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListItem.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#129 🔀 :: (#128) - 게스트로 이동 버튼 추가
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginButton.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LookAroundToGuestButton.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#130 🔀 :: (#125) - 페이지 네이션 구현
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentListResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/StudentInformation.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/StudentListModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/StudentModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetStudentListUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#133 🔀 :: (#125) - 필드명 변경
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/StudentInformation.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/StudentModel.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#135 🔀 :: (#132) - 자동로그인 변경
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/auth/response/AccessValidationResponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/AuthAPI.kt
  data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/auth/response/AccessValidationResponseModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/AccessValidationUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#136 🔀 :: (#134) - 메인리스트 페이지에서 학생 수 뜨도록 처리
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/MainScreenTopBar.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#137 🔀 :: (#127) - import the data of stack when user searching
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
  app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
  data/src/main/java/com/msg/sms/data/mapper/.gitinit
  data/src/main/java/com/msg/sms/data/remote/datasource/stack/RemoteStackDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/stack/RemoteStackDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/stack/reponse/SearchingDetailStackResponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/StackAPI.kt
  data/src/main/java/com/msg/sms/data/repository/StackRepositoryImpl.kt
  design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt
  design-system/src/main/java/com/msg/sms/design/component/topbar/SearchTopBar.kt
  domain/src/main/java/com/msg/sms/domain/model/stack/DetailStackListModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/StackRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/stack/GetSearchDetailStackUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/RecentlyAddedListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/SearchDetailStackViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#141 🔀 :: (#138) - setting the api that import user detail imformation
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForAnonymousResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForStudentResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForTeacherResponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForAnonymous.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForStudent.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForTeacher.kt
  domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetStudentDetailForStudentUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetUserDetailForAnonymousUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetUserDetailForTeacherUseCase.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#143 🔀 :: (#140) - 로그아웃, 회원탈퇴를 위한 바텀시트 UI제작
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_red_logout.xml
  design-system/src/main/res/drawable/ic_red_withdrawal.xml
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/ModalBottomSheetItem.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#145 🔀 :: (#144) - setting the api of withdrawal and logout
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/AuthAPI.kt
  data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
  design-system/src/main/java/com/msg/sms/design/component/item/RecentlyAddedItem.kt
  domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/DeleteTokenUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/LogoutUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/WithdrawalUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ✨ Feature

#147 🔀 :: (#142) - 아이템 클릭시 디테일 페이지 뜨도록 설정
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/StudentInformation.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/StudentModel.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/LogoutWithDrawalBottomSheetComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#149 🔀 :: (#146) - download the file of dream book when click dream book icon
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/AndroidDownloader.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/DownloadCompletedReceiver.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/Downloader.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#153 🔀 :: (#152) - convert the name from star to 소금
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListItem.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#155 🔀 :: (154) - Save the token when change page to detail stack search page
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#157 🔀 :: (#156) - when typing keyword, change text color of matched
  design-system/src/main/java/com/msg/sms/design/component/item/RecentlyAddedItem.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/RecentlyAddedListComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#159 🔀 :: (#148) - 디테일 페이지 바텀시트 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentInfoComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/data/StudentDetailData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#161 🔀 :: (#160) - Role 관련 정보 로컬 디비에 저장
  data/src/main/java/com/msg/sms/data/local/datasource/auth/LocalAuthDataSource.kt
  data/src/main/java/com/msg/sms/data/local/datasource/auth/LocalAuthDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/local/key/AuthPreferenceKey.kt
  data/src/main/java/com/msg/sms/data/remote/dto/auth/response/GAuthLoginResponse.kt
  data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/auth/response/GAuthLoginResponseModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/GetRoleInfoUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/SaveRoleInfoUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#164 🔀 :: (#162) - 저장한 Role정보에 따라 UI다르게 표시하도록 처리
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#163 🔀 :: (#158) - add splash page and change place of auto login
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-v31/splash.xml
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  design-system/src/main/res/drawable/ic_sms.xml
  presentation/build.gradle.kts
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#166 🔀 :: (#165) - 저장된 Role 정보들 로그아웃, 회원탈퇴 시에 정보 비워지도록 처리
  data/src/main/java/com/msg/sms/data/local/datasource/auth/LocalAuthDataSource.kt
  data/src/main/java/com/msg/sms/data/local/datasource/auth/LocalAuthDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/DeleteTokenUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/auth/SaveRoleInfoUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#170 🔀 :: (#167) - add the terms of use and remove the topbar icon
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/ShowTheTermsOfUse.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#169 🔀 :: (#168) - 게스트 상태일때 디테일 페이지 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#173 🔀 :: (#172) - change the color of cursors
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListItem.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#175 🔀 :: (#171) - 바텀시트 클릭시 리플 이슈 해결
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/BaseBottomSheetComponent.kt
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/ChooseProfilePictureBottomSheet.kt
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/LogoutWithDrawalBottomSheet.kt
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/ProfileBottomSheetComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/LogoutWithDrawalBottomSheetComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/ModalBottomSheetItem.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#177 🔀 :: (#174) - add self insert the detail stack
  design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt
  design-system/src/main/java/com/msg/sms/design/component/SmsChip.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/RecentlyAddedListComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#179 🔀 :: (#178) - control the keyboard position
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#180 🔀 :: (#176) - 게스트일 경우 뒤로가기 처리
  design-system/src/main/java/com/msg/sms/design/component/SmsChip.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#182 🔀 :: (#181) - 프로필 이미지 가져오는 작업
  app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
  app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
  app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/user/RemoteUserDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/user/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/user/response/GetProfileImageResponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/UserAPI.kt
  data/src/main/java/com/msg/sms/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/user/response/ProfileImageModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/UserRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/user/GetProfileImageUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/component/MainScreenTopBar.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#185 🔀 :: (#184) - control the screen according to keyboard
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/AndroidDownloader.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#187 🔀 :: (#186) - 다운로드된 파일 확장자 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/AndroidDownloader.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#200 🔀 :: (#186) - 파일 업로드 관련 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#199 🔀 :: (#198) - close softkeyboard when showing bottom sheet
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/hideKeyboard.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#201 🔀 :: (197) - change the wanted payroll
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#203 🔀 :: (#194) - 필터 버튼 클릭시 이벤트 추가
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_exclamation_mark.xml
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#202 🔀 :: (#196) - change the textfield checker
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/textFieldChecker.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#204 🔀 :: (#193) - change page when click top bar button
  design-system/src/main/java/com/msg/sms/design/component/topbar/TopBarComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#205 🔀 :: (#195) - control the app stack when click the back button
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#209 🔀 :: (#189) - 외국어 점수 텍스트 필드에 singleLine 추가
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#208 🔀 :: (#192) - 이메일, Url 정규식 검사 추가
  design-system/src/main/java/com/msg/sms/design/component/SmsDialog.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#212 🔀 :: (#211) - 취소버튼 없앨 수 있도록 로직 추가
  design-system/src/main/java/com/msg/sms/design/component/SmsDialog.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple
