Repository GSM-MSG/SMS-Android, pull requests merged in 2023-11, with the labels that each got.

#409 🔀:: (#408) - student information entry api refactoring
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/EnterStudentInformationRequest.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/EnterStudentInformationModel.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, 📝 Docs

#410 🔀 :: (#407) - Student information publishing refactoring
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/data/WorkConditionData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/info/StudentInfoComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/FillOutInformationTopBarComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/award/AwardBottomButtonComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/award/AwardComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/award/AwardDateBarComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/award/AwardInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/HopeWorkConditionBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/MilitarySelectorBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/certification/CertificationComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/foreignlanguage/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/militaryservice/MilitaryServiceComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/AddProjectButtonComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectDescriptionInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectIconInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectKeyTaskInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectNameInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectPreviewInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectRelatedLinksInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectScheduleInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsBottomButtonComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/schoollife/SchoolLifeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/workcondition/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/AwardData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/CertificationData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ForeignLanguageInfo.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ForeignLanguagesData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/MilitaryServiceData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProfileData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProjectInfo.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProjectRequiredDataInfo.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/SchoolLifeData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/AwardScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 1️⃣ Priority: High, 📝 Docs

#412 🔀 :: (#409) - Exceptions when a web browser does not exist in an overseas device
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/isBrowserInstalled.kt
  presentation/src/main/res/values-ko/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#413 🔀 :: (#406) 로그인한 유저의 마이페이지 nullable 처리
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/PutChangedProfileRequest.kt
  data/src/main/java/com/msg/sms/data/remote/dto/user/response/GetMyProfileResponse.kt
  domain/src/main/java/com/msg/sms/domain/model/user/response/MyProfileModel.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/PortfolioComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/MyProfileData.kt
Labels: 1️⃣ Priority: High, 🐞 Bug
