Repository GSM-MSG/SMS-Android, pull requests merged in 2023-08, with the labels that each got.

#226 🔀 :: (#222) - 필터링 정보 뷰모델에 전달되도록 로직 작성
  .idea/misc.xml
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetStudentListUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterItem.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorGroup.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/data/FilterClass.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/data/FilterDepartment.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/data/FilterGrade.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/data/FilterTypeOfEmployment.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#255 🔀 :: (#227) - 정보기입 프로그래스 바 퍼블리싱
  .idea/misc.xml
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/EnterStudentInformationRequest.kt
  data/src/main/java/com/msg/sms/data/repository/FileUploadRepositoryImpl.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  design-system/src/main/java/com/msg/sms/design/component/progressbar/FilloutStatusProgressBar.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/EnterStudentInformationModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/FileUploadRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/fileupload/DreamBookUploadUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/CertificationComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/FillOutInformationTopBarComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/MilitaryServiceComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/SchoolLifeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/SchoolLifeData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#259 🔀 :: (#258) - create my page bottom sheet
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_gray_logout_btn.xml
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/button/LogoutButton.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/button/WithdrawalButton.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/modal/MyPageBottomSheet.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#263 🔀 :: (#262) - version conflict resolve
  buildSrc/src/main/java/Versions.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#265 🔀 :: (#264) - create toggle on my page
  design-system/src/main/java/com/msg/sms/design/component/header/TitleHeader.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_chevron_down.xml
  design-system/src/main/res/drawable/ic_chevron_left.xml
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardNameComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardTypeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectNameComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/AwardSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#267 🔀 :: (#256) - 정보기입 프로젝트 파트 퍼블리싱
  .gitignore
  .idea/misc.xml
  design-system/src/main/java/com/msg/sms/design/component/toggle/ToggleComponent.kt
  design-system/src/main/res/drawable/ic_cancel.xml
  design-system/src/main/res/drawable/ic_toggle.xml
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/FillOutInformationTopBarComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectIconInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectKeyTaskInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectNameInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectPreviewInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectRelatedLinksInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectScheduleInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#269 🔀 :: (#268) - Date Picker 제작
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  design-system/build.gradle.kts
  design-system/src/main/java/com/msg/sms/design/component/picker/SmsDatePicker.kt
  design-system/src/main/java/com/msg/sms/design/theme/SMSTypography.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#271 🔀 :: (#270) - 프로젝트 프리뷰 갤러리 다중선택으로 변경
  design-system/src/main/java/com/msg/sms/design/modifier/smsClickable.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectPreviewInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#272 🔀 :: (#266) - create the data states of profile setion on my page
  design-system/src/main/java/com/msg/sms/design/component/button/DetailTechStackItem.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/DetailTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/EmailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/IntroduceComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/MajorComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/PictureComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/PortfolioComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/modal/MyPageBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProfileSection.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#280 🔀 :: (#276) - create data state of school life section on my page
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/life/SchoolScoreComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/SchoolLifeSection.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#281 🔀 :: (#277) - create the state of working condition section on my page
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WantPayComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WantWorkFormComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WorkLocationComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/WorkConditionSection.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#282 🔀 :: (#278) - create the state of military section on my page
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/military/MilitaryServiceTypeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/MilitaryServiceSection.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#283 🔀 :: (#279) - create the state of certification and foreign language section on my page
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/certification/CertificationsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/language/ForeignLanguagesComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/CertificationsSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ForeignLanguagesSection.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#291 🔀 :: (#285) - implement the feature of managing project data section on my page
  design-system/src/main/java/com/msg/sms/design/component/header/TitleHeader.kt
  design-system/src/main/java/com/msg/sms/design/component/indicator/PreviewImageIndicator.kt
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  design-system/src/main/res/drawable/ic_gallery_btn.xml
  presentation/src/main/java/com/sms/presentation/main/ui/detail/data/AwardNameData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/data/ExpandableProjectData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/data/ProjectNameData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectIconComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectKeyTaskComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectNameComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectPreviewComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectRelatedLinksComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#294 🔀 :: (#292) - create an account withdrawal and logout feature
  design-system/src/main/java/com/msg/sms/design/component/SmsDialog.kt
  design-system/src/main/java/com/msg/sms/design/component/button/BoxButton.kt
  design-system/src/main/java/com/msg/sms/design/component/button/ButtonState.kt
  design-system/src/main/java/com/msg/sms/design/component/button/RoundedButton.kt
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/DetailTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#293 🔀 :: (#275) - 정보기입 프로젝트 관련 데이터 처리
  design-system/src/main/java/com/msg/sms/design/component/toggle/ToggleComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/FillOutInformationTopBarComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/certification/CertificationComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/foreignlanguage/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/militaryservice/MilitaryServiceComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/AddProjectButtonComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectIconInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectKeyTaskInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectNameInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectPreviewInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectRelatedLinksInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectScheduleInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsBottomButtonComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/schoollife/SchoolLifeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/workcondition/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProjectInfo.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#297 🔀 ::(#295) - Change the parameter to reuse component to use the detail stack search
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/SearchDetailStackViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#299 🔀 :: (#298) - create the data state of award on mypage
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardDateComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardNameComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardTypeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/AwardSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ExpandableAwardDate.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ExpandableProjectData.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#301 🔀 :: (#290) - Date Picker 제작
  design-system/src/main/java/com/msg/sms/design/component/picker/SmsDatePicker.kt
  design-system/src/main/java/com/msg/sms/design/component/picker/SmsPicker.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#304 🔀 :: (#302) - 바텀 시트 관련 로직 리팩토링
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  design-system/build.gradle.kts
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/ChooseProfilePictureBottomSheet.kt
  design-system/src/main/java/com/msg/sms/design/component/picker/SmsDatePicker.kt
  design-system/src/main/java/com/msg/sms/design/component/picker/SmsPicker.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/FillOutInformationTopBarComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/DatePickerBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/MajorSelectorBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/MilitarySelectorBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/PhotoPickBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/militaryservice/MilitaryServiceComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectIconInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsBottomButtonComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/workcondition/WorkConditionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#303 🔀 :: (#300) - create the feature of detail stack searching
  data/src/main/java/com/msg/sms/data/remote/dto/stack/reponse/SearchingDetailStackResponse.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/screen/FilterScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/DetailTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProfileSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ExpandableProjectData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ProjectTechStack.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/SearchDetailStackViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#309 🔀 :: (#307) - get major list data on my page
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#312 🔀 :: (#296) - 정보기입 프로필 부분 세부스택 그리드로 변경
  gradle.properties
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#316 🔀 :: (#315) - 프로젝트 설명 인풋 컴포넌트 및 상태 추가
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectDescriptionInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProjectInfo.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#318 🔀 :: (#317) - 프로젝트 날짜 control 로직 작성
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#319 🔀 :: (#313) - 세부스택 최대 갯수 제한
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectPreviewInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProfileData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#322 🔀 :: (#311) - create component of not added project imformation
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/data/ProjectData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectDescriptionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/MyProfileViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#325 🔀 :: (#324) - date picker 디자인 시스템에 생성
  design-system/src/main/java/com/msg/sms/design/component/bottomsheet/DatePickerBottomSheet.kt
  design-system/src/main/java/com/msg/sms/design/component/picker/SmsDatePicker.kt
  design-system/src/main/java/com/msg/sms/design/component/picker/SmsPicker.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#323 🔀 :: (#310) - 정보기입한 데이터를 서버에 전송
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/EnterStudentInformationRequest.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/award/AwardComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/foreignlanguage/ForeignLanguageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/AwardData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ForeignLanguageInfo.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ForeignLanguagesData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/AwardScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#327 🔀 :: (314) - 정보기입 프로젝트 필수값 마킹
  .idea/gradle.xml
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectDescriptionInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectIconInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectNameInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectScheduleInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProjectRequiredDataInfo.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#329 🔀 :: (#328) - 프로젝트 날짜 관련 이슈 해결
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/ProjectDateData.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/ProjectDateModel.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProjectInfo.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#331 🔀 :: (#330) - 직접 입력한 전공이 서버에 전달되지 않는 문제 해결
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#326 🔀 :: (#308) - post the data of modified by user
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/CertificateData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/PutChangedProfileRequest.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/user/response/MyProfileModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/PutChangedProfileUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/button/SaveButtonComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/military/MilitaryBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectIconComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectScheduleComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WorkingConditionBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProfileSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/WorkConditionSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/FormOfEmployment.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/MilitaryService.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/MyProfileData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/changeCurrentTime.kt
  presentation/src/main/java/com/sms/presentation/main/ui/util/createFileFromBitmap.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/MyProfileViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#333 🔀 :: (#332) - 메인 페이지의 리스트가 나오지 않는 문제 해결
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentListResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/StudentInformation.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#335 🔀 :: (#334) - 디테일 페이지 관련 이슈 해결
  data/src/main/java/com/msg/sms/data/remote/dto/common/CertificateData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/common/PrizeData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/common/ProjectData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/common/ProjectDateData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/common/ProjectRelatedLinkData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/CertificateData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/EnterStudentInformationRequest.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/PrizeData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/ProjectDateData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/ProjectRelatedLinkData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/request/PutChangedProfileRequest.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForAnonymousResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForStudentResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForTeacherResponse.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  domain/src/main/java/com/msg/sms/domain/model/common/CertificateModel.kt
  domain/src/main/java/com/msg/sms/domain/model/common/PrizeModel.kt
  domain/src/main/java/com/msg/sms/domain/model/common/ProjectDateModel.kt
  domain/src/main/java/com/msg/sms/domain/model/common/ProjectRelatedLinkModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/CertificateInformationModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/EnterStudentInformationModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/ProjectModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForAnonymous.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForAnonymousModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForStudentModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForTeacherModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentInfoComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/data/CertificateData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectDescriptionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectInfoTopBar.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectKeyTaskComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectLinkComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectPreviewComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectRelatedLinksComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectTechStacksComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/data/StudentDetailData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#340 🔀 :: (#338) - 바텀 시트 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 0️⃣ Priority: Critical, 📝 Docs

#341 🔀 :: (#339) - 필터 기본값 보내지 않도록 로직 변경
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#342 🔀 :: (#336) - 세부스택으로 필터 검사하는 로직 추가
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterDetailStackSearchComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSearchTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/screen/FilterScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#345 🔀 :: (#344) - 디테일 페이지 UI수정
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/award/AwardComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/info/StudentInfoComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/profile/StudentProfileComponent.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#346 🔀 :: (#343) - 필터 적용 이슈 해결
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectionControlsGroup.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorGroup.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSliderGroup.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/screen/FilterScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#348 🔀 :: (#347) - 정보기입 세부스택 입력한 값 안나오는 에러 수정
  data/src/main/java/com/msg/sms/data/remote/dto/stack/reponse/SearchingDetailStackResponse.kt
  domain/src/main/java/com/msg/sms/domain/model/stack/DetailStackListModel.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#350 🔀 :: (#349) - 버전코드, 버전이름 수정
  buildSrc/src/main/java/ProjectProperties.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy
