Repository GSM-MSG/SMS-Android, pull requests merged in 2024-08, with the labels that each got.

#453 🔀 :: (#452) - Changed app_name
  app/src/main/res/values/strings.xml
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#455 🔀 :: (#454) - Use productFlavors
  app/build.gradle.kts
Labels: 2️⃣ Priority: Medium, ⚡️ Simple, ⚡️performance

#487 🔀 :: (#486) - 인증제 페이지 진입시 기본값을 설정하도록 하였습니다.
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/component/AuthenticationField.kt
Labels: 1️⃣ Priority: High, ⚡️performance, ✨ Feature

#437 🔀 :: (#436) - version update 1.2.1
  buildSrc/src/main/java/ProjectProperties.kt
  presentation/src/main/AndroidManifest.xml
Labels: 1️⃣ Priority: High
