Repository GSM-MSG/SMS-Android, pull requests merged in 2024-06, with the labels that each got.

#439 🔀 인증제를 추가하는 컴포넌트를 구현합니다.
  .gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/index.pb
  .idea/vcs.xml
  design-system/src/main/java/com/msg/sms/design/component/header/TitleHeader.kt
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_arrow_down.xml
  design-system/src/main/res/drawable/ic_calendar.xml
  design-system/src/main/res/drawable/ic_file.xml
  design-system/src/main/res/drawable/ic_plus.xml
  design-system/src/main/res/drawable/ic_xmark.xml
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/component/AuthenticationArea.kt
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/component/AuthenticationSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/component/FieldItem.kt
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/enum/InputItemEnum.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#435 🔀 :: (#428) - refactor textfield component
  .gitignore
  .idea/gradle.xml
  .idea/vcs.xml
  design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt
  design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
  design-system/src/main/java/com/msg/sms/design/component/topbar/SearchTopBar.kt
  gradlew.bat
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_authentication/component/ActivityDescriptionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_authentication/component/ActivityTitleComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileTechStackInputComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSearchTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSliderComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterTextFiled.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardDateComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardNameComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardTypeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/certification/CertificationsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/language/ForeignLanguagesComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/life/SchoolScoreComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/military/MilitaryServiceTypeComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/DetailTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/DisplaySearchBar.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/EmailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/IntroduceComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/MajorComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/PortfolioComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectDescriptionComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectKeyTaskComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectNameComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectRelatedLinksComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectScheduleComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectTechStackComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WantPayComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WantWorkFormComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WorkLocationComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/teacher_registration/component/ClassSelectorComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/teacher_registration/component/GradeSelectorComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/teacher_registration/component/PositionSelectorComponent.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#441 🔀 :: (#440) - create file download component
  design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
  design-system/src/main/res/drawable/ic_file.xml
  design-system/src/main/res/drawable/ic_folder.xml
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/component/AuthenticationArea.kt
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/component/AuthenticationSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/component/FileDownLoadComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/authentication/component/FileItem.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#444 🔀 :: (#443) - fix main list copy issue
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 0️⃣ Priority: Critical

#448 🔀 :: (#447) - add default component
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/certification/CertificationsComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/language/ForeignLanguagesComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WorkLocationComponent.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/MyProfileViewModel.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#450 🔀 :: (#449) - modify dialog cancel button color
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#451 🔀 :: create remove data on click else student's detail page
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSource.kt
  data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSourceImpl.kt
  data/src/main/java/com/msg/sms/data/remote/dto/common/ProjectData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/common/ProjectDateData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/common/ProjectRelatedLinkData.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForAnonymousResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForStudentResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/user/response/LinkResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/user/response/PrizeResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/user/response/ProgressResponse.kt
  data/src/main/java/com/msg/sms/data/remote/dto/user/response/ProjectReseponse.kt
  data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
  data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
  design-system/src/main/java/com/msg/sms/design/component/profile/ProfileImageComponent.kt
  domain/src/main/java/com/msg/sms/domain/model/common/LinkModel.kt
  domain/src/main/java/com/msg/sms/domain/model/common/ProjectDateModel.kt
  domain/src/main/java/com/msg/sms/domain/model/common/ProjectModel.kt
  domain/src/main/java/com/msg/sms/domain/model/common/ProjectRelatedLinkModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/request/ProjectModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForAnonymousModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForStudentModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForTeacherModel.kt
  domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentModel.kt
  domain/src/main/java/com/msg/sms/domain/model/user/response/ActivityDuration.kt
  domain/src/main/java/com/msg/sms/domain/model/user/response/MyProfileModel.kt
  domain/src/main/java/com/msg/sms/domain/model/user/response/PrizeModel.kt
  domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetStudentDetailForStudentUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetUserDetailForAnonymousUseCase.kt
  domain/src/main/java/com/msg/sms/domain/usecase/student/GetUserDetailForTeacherUseCase.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/award/AwardComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/data/ProjectData.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/profile/StudentProfileComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectInfoTopBar.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectLinkComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectListComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectRelatedLinksComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectScheduleComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ActivityDuration.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/MyProfileViewModel.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
Labels: 2️⃣ Priority: Medium

#465 🔀 :: (#463) - publishing portfolio file upload
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/MajorSelectorBottomSheet.kt
  presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/PortfolioComponent.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProfileSection.kt
  presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/PortfolioType.kt
  presentation/src/main/java/com/sms/presentation/main/viewmodel/MyProfileViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature
